export const actionFeedback = {
  wave: "你好呀！",
  jump: "跳得好高！",
  eat: "谢谢！苹果真好吃。",
  openDoor: "门打开啦，欢迎进来！",
  closeDoor: "门关好啦。",
  sunset: "天黑啦，我们的小世界要睡觉了吗？",
  sunrise: "早上好，太阳出来啦！",
  shake: "风来啦！",
  move: "汪！我来找你啦！",
  feed: "好吃！",
  dance: "跟着节奏跳舞吧！",
  spin: "转一圈，世界也跟着转起来！",
  cheer: "太棒啦，我们一起欢呼！",
  rest: "回到温暖的房间休息一会儿吧。",
  leaveRoom: "休息好啦，出去活动一下！",
};

export const actionDurations = {
  wave: 1200,
  jump: 900,
  eat: 1000,
  openDoor: 900,
  closeDoor: 900,
  sunset: 1600,
  sunrise: 1600,
  shake: 1100,
  move: 1400,
  feed: 2100,
  dance: 1800,
  spin: 1100,
  cheer: 1300,
  rest: 1800,
  leaveRoom: 1000,
};
